### ISSUE TITLE
win32 File::Spec::Functions::rel2abs signature off-by-one SP (wrong hassig)

### ISSUE THREAD

**Issue by bulk88** [perl11/cperl#151] opened 2016-06-04 16:30 UTC
https://ci.appveyor.com/project/rurban/cperl/build/5.24.0.1223/job/p6qutdc4a9sg0cgl

```
    link -out:..\miniperl.exe @C:\Users\appveyor\AppData\Local\Temp\1\nm4939.tmp
Generating code
Finished generating code
if exist ..\miniperl.exe.manifest mt -nologo -manifest ..\miniperl.exe.manifest -outputresource:..\miniperl.exe;1 && if exist ..\miniperl.exe.manifest del ..\miniperl.exe.manifest
..\miniperl.exe -I..\lib -f ..\write_buildcustomize.pl ..
Prototype mismatch: sub Cwd::fastgetcwd: none vs () at dist/PathTools/Cwd.pm line 690.
Prototype mismatch: sub Cwd::cwd: none vs () at dist/PathTools/Cwd.pm line 690.
Can't locate object method "file_name_is_absolute" via package "lib" (perhaps you forgot to load "lib"?) at dist/PathTools/lib/File/Spec/Win32.pm line 313.
NMAKE : fatal error U1077: '..\miniperl.exe' : return code '0xff'
Stop.
Command exited with code 2
```

The "Prototype mismatch: sub Cwd::cwd: none vs () at dist/PathTools/Cwd.pm line 690." is a warning that I dont think affects the problem. a `sub cwd ();` fixes it in `dist/PathTools/Cwd.pm`.

A backtrace shows 

C:\sources\cperl\win32>..\miniperl.exe -I..\lib -f ..\write_buildcustomize.pl ..

```
        File::Spec::Win32::rel2abs(** Incomplete caller override detected; @DB::
args were not set **) called at dist/PathTools/lib/File/Spec/Functions.pm line 6
2
        File::Spec::Functions::__ANON__("lib", "C:/sources/cperl") called at ..\
write_buildcustomize.pl line 68
SV = PV(0x958348) at 0xa37ab0
  REFCNT = 1
  FLAGS = 0x10004403 (POK,IsCOW,pPOK)
  PV = 0xa19fe8 "lib"\0
  CUR = 3
  LEN = 7
  COW_REFCNT = 1
Can't locate object method "file_name_is_absolute" via package "lib" (perhaps yo
u forgot to load "lib"?) at dist/PathTools/lib/File/Spec/Win32.pm line 317.
```

So method `rel2abs` in dist/PathTools/lib/File/Spec/Win32.pm isn't getting a class name from the sub to method translator stub sub created in File::Spec::Functions

```
foreach my $meth (@EXPORT, @EXPORT_OK) {
    my $sub = File::Spec->can($meth);
    no strict 'refs';
    if (exists($udeps{$meth}) && $sub == File::Spec::Unix->can($meth) &&
        !(grep {
        File::Spec->can($_) != File::Spec::Unix->can($_)
        } @{$udeps{$meth}}) &&
        defined(&{"File::Spec::Unix::_fn_$meth"})) {
    *{$meth} = \&{"File::Spec::Unix::_fn_$meth"};
    } else {
    *{$meth} = sub {&$sub('File::Spec', @_)};
    }
}
```

The `File::Spec::Functions::rel2abs($_, $cwd)` in write_buildcustomize.pl seems correct as the idiom is used on CPAN in many places http://grep.cpan.me/?q=%3A%3Arel2abs . I dont know enough about prototypes/sigs/cperl sigs to understand the problem. But it seems like `*{$meth} = sub {&$sub('File::Spec', @_)};` is actually executing like`*{$meth} = sub {&$sub(@_)};`

**Comment by rurban** [comment] 2016-06-06 06:23
Yes, I know. I'm already working on that last 5.24 blocker.
The problem is actually inside pp_signature, with msvc only.

good case: (-DXlvst on linux/darwin)

```
  CX 3: SUB    => PV("File::Spec"\0)  PV("lib"\0)  PV("/usr/src/perl/blead/cperl"\0)  
  retop=leavesub

(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)    signature($self, str $path, $base?)
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigpad padp 7bc15f00 curpad[1] $self
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigconst argp 7bc00e60
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigcopy padp 7bc15f00 $self = argp 7bc00e60
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigconst argp 7c3a3800
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigcopy padp 7bc15f40 $path = argp 7c3a3800
(92243:dist/PathTools/lib/File/Spec/Functions.pm:64)      sigcopy padp 7bc15fa0 $base = argp 7c3a0d60
```

3 args copied, all good.

bad case: (-DXlvst on msvc)

```
  CX 3: SUB    => PV("File::Spec"\0)  PV("lib"\0)  PV("C:/cygwin/usr/src/perl/blead/cperl"\0)  
  retop=leavesub

(2904:dist/PathTools/lib/File/Spec/Functions.pm:64) signature($self, str $path, $base?)
(2904:dist/PathTools/lib/File/Spec/Functions.pm:64)   sigpad padp 9fe5e0 curpad[1] $self
(2904:dist/PathTools/lib/File/Spec/Functions.pm:64)   sigconst argp 9bd2a8
(2904:dist/PathTools/lib/File/Spec/Functions.pm:64)   sigcopy padp 9fe5e0 $self = argp 9bd2a8
(2904:dist/PathTools/lib/File/Spec/Functions.pm:64)   sigcopy padp 9fe5f0 $path = argp 9b4f28
```

So we are missing a whole argument here, the SP is off-by-one. There are only 2 sigcopy's, not 3.

**Comment by rurban** [comment] 2016-06-06 08:14
The root cause was a missing cBOOL for CvHASSIG(cv) which returns an int > char, and on MSVC only the assignment to bool set it to 0 and not 1. So on MSVC hassig was always false, and the args were always copied from @_ and not from the CX savearray.

gcc and clang really needs to add some kind of new -Wcompat warning for this.

**Comment by rurban** [comment] 2016-06-06 21:05
Fixed in `smoke/gh151-msvc-bool` and `master`, will be in v5.24.0c

**Closed as completed by rurban** 2016-06-06 21:05 UTC
Labels: bug, blocking
