### ISSUE TITLE
Configure with default values fails on using -fstack-protector

### ISSUE THREAD

**Issue by jorisgeer** [perl11/cperl#296] opened 2017-06-19 00:44 UTC
When running Configure on linux, specifying gcc, it fails as it tries to supply -fstack-protector to the ld linker

./Configure -des -Dcc=gcc -Dinc_version_list=none -Dprefix=/home/joris -A ccflags="-DPERL_PERTURB_KEYS_DISABLED -DNO_HASH_SEED"
[..]
ld -o generate_uudmap -fstack-protector -L/usr/local/lib generate_uudmap.o -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc 
ld: -f may not be used without -shared
make: *** [generate_uudmap] Error 1

Further, the Configure script does not return an error status.

When reconfiguring and specifying the loinker flags without -fstack-protector, it fails on
ld -o generate_uudmap -L/usr/local/lib generate_uudmap.o -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc 
ld: cannot find -lpthread
ld: cannot find -lnsl
ld: cannot find -ldl
ld: cannot find -lm
ld: cannot find -lcrypt
ld: cannot find -lutil
ld: cannot find -lc
make: *** [generate_uudmap] Error 1

So apparently the main issue is that 'ld' is used as linker instead of 'gcc', yet using the gcc commandline flags

**Comment by rurban** [comment] 2017-06-19 09:19
Cannot reproduce. Can you attach the full Configure log please? 
There are some old obscure logical paths, which do use ld=ld, such as non ELF systems: bin_ELF=undef "I'll use ld to build dynamic libraries"
or usedl=undef. And the exact cperl version/commit please.

Your error `ld: -f may not be used without -shared` is esp. probed against, to ensure that -fstack-protector is not used with ld.

**Comment by jorisgeer** [comment] 2017-06-20 07:34
I am installing the release cperl-5.26.0 date 25 April 2017, as unpacked from the 'source' tar
Running on Linux Mint
Issue does not occur after cleaning directory and reconfiguring

**Comment by rurban** [comment] 2017-06-20 07:59
Interesting. Maybe some left over config.over, config.sh or Policy.sh which had no usedl. 
Closing, but thanks for the report anyway.

**Closed as completed by rurban** 2017-06-20 07:59 UTC
Labels: bug
