### ISSUE TITLE
5.22.2 no longer installs a .../bin/perl executable

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#144] opened 2016-05-19 17:10 UTC
`perlbrew` (and likely other install managers) expect `.../bin/perl` to be created as part of the compilation. After [this commit](https://github.com/perl11/cperl/commit/93700cfea3) that is no longer the case, resulting in [inability to "switch" to the newly compiled cperl](https://travis-ci.org/ribasushi/dbix-class/jobs/131437724#L472-L476).

Cheers

**Comment by rurban** [comment] 2016-05-21 07:47
On the other hand cperl needs to coexist with perl packages so I cannot just overwrite it. This is needed for native packages like debian, rpm, ... which is more important than perlbrew oddities. EWontfix

Needs to be changed by perlbrew

**Comment by ribasushi** [comment] 2016-05-23 07:10
>  which is more important than perlbrew oddities

I would agree if the above were the case. You are missing [all of this](http://grep.cpan.me/?q=%5E%23%21%2Fusr%2Fbin%2Fenv+perl), which will break regardless of which _"many perls in PATH"_ handler one is using (perlbrew, plenv, etc).

I strongly urge you to bring back the `perl` entry, and instead provide a `configure` knowb of some sort for distro packagers to set.

**Comment by rurban** [comment] 2016-05-23 07:14
That's true. Maybe we should add the symlink to bin/perl and add special removal lines for the packaging recipes.

**Comment by ribasushi** [comment] 2016-05-30 10:43
Before releasing the next version - please point me to an RC ( be it tarball, tag, or just a git sha) so I can put it through the paces on my smoker.

**Comment by ribasushi** [comment] 2016-06-02 17:37
Finally getting back to this, will have results against `master` in about an hour (making it a permanent test fixture, will take some tweaking).

**Comment by ribasushi** [comment] 2016-06-02 19:33
Having trouble... still investigating on and off. Will have another update in an hour or so.

**Comment by rurban** [comment] 2016-06-02 19:37
Did perlbrew create the perl binary? 
I uploaded a src tarball to https://github.com/perl11/cperl/releases/download/cperl-5.22.3-RC1/cperl-5.22.3.tar.bz2 esp. for perlbrew to test.

**Comment by ribasushi** [comment] 2016-06-02 20:14
Confirmed - it does not :/
I was trying with https://github.com/perl11/cperl/commit/5f87ffbe14

**Comment by ribasushi** [comment] 2016-06-02 20:39
The rest [is golden](https://travis-ci.org/ribasushi/dbix-class/jobs/134854162#L691)

**Comment by rurban** [comment] 2016-06-03 07:17
Yes, `bin/perl` is still not created. Which is fine for my packages, but not for perlbrew. I'll rather provide cperl support to perlbrew, working on it...
That way you can also install any cperl-$version, perlbrew knowing about the download location.

**Comment by ribasushi** [comment] 2016-06-03 10:55
Let me know when this is ready to re-test.

A side note - it would help if you don't close issues right away, but keep it open until the commit-to-test lands: this way I can be alerted automatically when to look.

**Comment by rurban** [comment] 2016-06-03 22:17
One remaining part of the issue is `installperl` on windows, exiting with "perl isn't executable".
The other part will be fixed in `rurban/App-perlbrew`.

**Comment by rurban** [comment] 2016-06-08 08:12
Windows was fixed, rurban/App-perlbrew after the 5.24 release

**Closed as completed by rurban** 2016-06-08 08:12 UTC
Labels: regression
