### ISSUE TITLE
recycle eval-string code and data

### ISSUE THREAD

**Issue by sten22** [perl11/cperl#178] opened 2016-07-07 05:46 UTC
This is not related to cperl, but p5p don't care about it.
Original bug posted by bulk88 here: https://rt.perl.org/Public/Bug/Display.html?id=121274

I've rewrite test script to show dramatic memory leak:

```
log_mem_usage("start");

for(1..20) {
    eval 'sub create_big_array' . $_ . ' {
        my @big_array;
        push @big_array, $_ for 1 .. 10_000_000;
        return;
    }';

    "create_big_array$_"->();

    log_mem_usage("after $_");
}

sub log_mem_usage {
    warn $_[0], " ", `ps -p $$ -o vsz,rss`;
}
```

output(looks similar for perl-5.8.9 and cperl-5.24):

```
start      VSZ    RSS
 2445916   1792
after 1      VSZ    RSS
 3049324 386004
after 2      VSZ    RSS
 3140652 465880
after 3      VSZ    RSS
 3223364 546640
after 4      VSZ    RSS
 3302460 625896
after 5      VSZ    RSS
 3376936 702688
after 6      VSZ    RSS
 3440840 785880
after 7      VSZ    RSS
 3542144 853908
after 8      VSZ    RSS
 3622140 861712
after 9      VSZ    RSS
 3701856 830184
after 10      VSZ    RSS
 3776332 731268
after 11      VSZ    RSS
 3839864 786372
after 12      VSZ    RSS
 3941564 829184
after 13      VSZ    RSS
 4021280 810856
after 14      VSZ    RSS
 4095756 847128
after 15      VSZ    RSS
 4159288 905216
after 16      VSZ    RSS
 4260988 910256
after 17      VSZ    RSS
 4340704 913028
after 18      VSZ    RSS
 4415180 929988
after 19      VSZ    RSS
 4478712 968668
after 20      VSZ    RSS
 4580412 1055332
```

actualy it is not related to arrays:

```
    eval 'sub create_big_array' . $_ . ' {
        my $s = "x" x 100000000;
        return;
    }';
```

cause same leak

**Comment by rurban** [comment] 2016-07-07 07:09
It's not really a leak. eval-string created global code is never recycled at scope-end, only released during global destruction.
This is because all non-lexical subs are global, thus must be kept in memory.
If you want them to go out of scope use lexical subs.

Unfortunately all simple macro schemes, via string builders, as used by most perl oo frameworks, e.g. Moose use this to create global methods.

What you need to do is to undef such unwanted globals subs after usage.

If you need to use globals subs, try at least to globalize the memory hogs. With my, our local they are allocated separately. If global there's only big instance kept in memory, but you loose encapsulation.

not a bug

**Comment by sten22** [comment] 2016-07-07 07:27
I used eval only for creating 20 "real" subs, if you create manual 20 subs there will be same effect

**Comment by sten22** [comment] 2016-07-07 08:07
with lexical sub it doubled twice and never return:

```
log_mem_usage("start");
{
    (sub { my $s = "x" x 500000000; })->();
}
log_mem_usage("after");

start      VSZ    RSS
 2924660 489884
after       VSZ    RSS
 3422160 978212
```

As I understand first it preallocated at compile time, then called again, we can avoid this behavior using variable length:

```
log_mem_usage("start");
{
    (sub { my $i = 500000000; my $s = "x" x $i; })->();
}
log_mem_usage("after");

start      VSZ    RSS
 2445588   1604
after       VSZ    RSS
 2933876 489936
```

but mem also never return:

```
log_mem_usage("start");
(sub { my $i = 500000000; my $s = "x" x $i; })->(); log_mem_usage("after 1");
(sub { my $i = 500000000; my $s = "x" x $i; })->(); log_mem_usage("after 2");
(sub { my $i = 500000000; my $s = "x" x $i; })->(); log_mem_usage("after 3");
(sub { my $i = 500000000; my $s = "x" x $i; })->(); log_mem_usage("after 4");
(sub { my $i = 500000000; my $s = "x" x $i; })->(); log_mem_usage("after 5");

start      VSZ    RSS
 2455828   1644
after 1      VSZ    RSS
 2944116 489972
after 2      VSZ    RSS
 3432400 778820
after 3      VSZ    RSS
 3920684 1044500
after 4      VSZ    RSS
 4408968 1194196
after 5      VSZ    RSS
 4897252 1267140
```

one more strange example use 4gb+:

```
perl -e 'sub { my $t = "x" x (10 ** 10) }'
```

**Comment by rurban** [comment] 2016-07-07 08:10
As I explained, try it without the my in the sub. Then the data is only one global instance, not so many.

What you call lexical sub was not a lexical sub. Currently they need to be named.

```
valgrind --tool=massif ./perl -Ilib -E'{my sub x { my $s = "x" x 500000000;} x;}'
grep mem_heap_B massif.out.34973

=>
mem_heap_B=381025
mem_heap_B=500382567
mem_heap_B=500382271
mem_heap_B=1000372762
mem_heap_B=366861
```

or using your code with lexical subs:

```
$ cperl -mexperimental=lexical_subs -E'sub ps{warn $_[0], " ", `ps -p $$ -o vsz,rss`;} 
{my sub x { my $s = "x" x 500000000;} ps 1;x;ps 2;} ps 3'
1      VSZ    RSS
 2935904 490936
2      VSZ    RSS
 3426236 979264
3      VSZ    RSS
 2937952 490984
```

with undef:

```
./perl -Ilib -mexperimental=lexical_subs -E'sub ps{warn $_[0], " ", `ps -p $$ -o vsz,rss`;} 
no strict; for (0..3) { eval "sub x$_ { my \$s = q(x) x 500000000;}"; ps $_."b"; "x$_"->(); 
ps $_."a"; eval "undef \&x$_"; ps $_."del"} ps "after"'

0b      VSZ    RSS
 2926688 492132
0a      VSZ    RSS
 3424188 980444
0del      VSZ    RSS
 2447620   3896
1b      VSZ    RSS
 2935904 492184
1a      VSZ    RSS
 3424188 980468
1del      VSZ    RSS
 2447620   3900
2b      VSZ    RSS
 2935904 492188
2a      VSZ    RSS
 3424188 980472
2del      VSZ    RSS
 2456836   3928
3b      VSZ    RSS
 2945120 492216
3a      VSZ    RSS
 3433404 980500
3del      VSZ    RSS
 2456836   3932
after      VSZ    RSS
 2456836   3932
```

you can also undef it in a separate loop, when you don't need those subs anymore.

with a global it's not as good as via explicit undef'ing of course:

```
$ ./perl -Ilib -mexperimental=lexical_subs -E'sub ps{warn $_[0], " ", `ps -p $$ -o vsz,rss`;} 
no strict; 
for (0..3) { eval "sub x$_ { \$s = q(x) x 500000000;}"; ps $_."b"; "x$_"->(); ps $_."a"; } 
ps "after"'

0b      VSZ    RSS
 2926688 492128
0a      VSZ    RSS
 3424188 980440
1b      VSZ    RSS
 3912472 1468744
1a      VSZ    RSS
 3912472 1468744
2b      VSZ    RSS
 4400756 1957028
2a      VSZ    RSS
 4400756 1957028
3b      VSZ    RSS
 4890064 2445332
3a      VSZ    RSS
 4891088 2445348
after      VSZ    RSS
 4891088 2445348
```

**Comment by sten22** [comment] 2016-07-07 08:37
ok, with real lexical subs it just 3 time triple:

```
log_mem_usage("start");
$s = "x" x 500000000;
log_mem_usage("create");

{  my sub process { my $t = "avoid cow" . shift }; process($s); log_mem_usage("after 1") }
{  my sub process2 { my $t = "avoid cow" . shift }; process2($s); log_mem_usage("after 2") };
{  my sub process3 { my $t = "avoid cow" . shift }; process3($s); log_mem_usage("after 3") };

start      VSZ    RSS
 2934204 490120
create      VSZ    RSS
 3422488 978408
after 1      VSZ    RSS
 3910772 1466704
after 2      VSZ    RSS
 3919988 1366944
after 3      VSZ    RSS
 3919988 1414124
```

but real scripts(e.g. 99% code from cpan) looks like this:

```
log_mem_usage("start");
$s = "x" x 500000000;
log_mem_usage("create");

sub process1 { my $t = "avoid cow" . shift };
sub process2 { my $t = "avoid cow" . shift };
sub process3 { my $t = "avoid cow" . shift };
sub process4 { my $t = "avoid cow" . shift };
sub process5 { my $t = "avoid cow" . shift };

process1($s); log_mem_usage("after 1");
process2($s); log_mem_usage("after 2");
process3($s); log_mem_usage("after 3");
process4($s); log_mem_usage("after 4");
process5($s); log_mem_usage("after 5");

start      VSZ    RSS
 2944444 490140
create      VSZ    RSS
 3440920 928500
after 1      VSZ    RSS
 3929204 1436808
after 2      VSZ    RSS
 4417488 1629832
after 3      VSZ    RSS
 4905772 1790792
after 4      VSZ    RSS
 5394056 1864940
after 5      VSZ    RSS
 5882340 2033088
```

so when big data chunk is appear in each sub it grow and never return memory back, and memory usage depend on how many subs you have
is it acceptable ?

**Comment by sten22** [comment] 2016-07-07 08:41
I see I can free memory manual:

```
sub process1 { my $t = "avoid cow" . shift; undef $t };
sub process2 { my $t = "avoid cow" . shift; undef $t };
sub process3 { my $t = "avoid cow" . shift; undef $t };
sub process4 { my $t = "avoid cow" . shift; undef $t };
sub process5 { my $t = "avoid cow" . shift; undef $t };

start      VSZ    RSS
 2944444 490132
create      VSZ    RSS
 3440920 902536
after 1      VSZ    RSS
 3440920 896156
after 2      VSZ    RSS
 3440920 896196
after 3      VSZ    RSS
 3440920 896196
after 4      VSZ    RSS
 3440920 896196
after 5      VSZ    RSS
 3440920 896196
```

why don't do this automaticaly?

**Comment by rurban** [comment] 2016-07-07 12:51
This is now a different case. Here we have a couple of global subs, which are only destroyed at the end.
All of them carry lexicals in their pad. These lexicals have to be carried around also,
because you might close over them, and need those distinct values.

still not a bug.

**Closed as completed by rurban** 2016-07-07 12:51 UTC
Labels: wontfix

**Comment by sten22** [comment] 2016-07-08 06:47
Well, lets return to arrays, why this code leaking?

```
my $Na = 5_000_000;

log_mem_usage("start");

my $arr;
for(1..10) {
    $arr = [ ];
    push @$arr, $_ foreach 1 .. $Na;
    log_mem_usage("create array");

    undef $arr;
    log_mem_usage("free array");
};

sub log_mem_usage {
    warn $_[0], " ", `ps -p $$ -o vsz,rss`;
}

start      VSZ    RSS
 2436372   1592
create array      VSZ    RSS
 2606616 166788
free array      VSZ    RSS
 2606616 166920
create array      VSZ    RSS
 2652824 213256
free array      VSZ    RSS
 2652824 213384
create array      VSZ    RSS
 2700056 259476
free array      VSZ    RSS
 2700056 259604
create array      VSZ    RSS
 2746264 305684
free array      VSZ    RSS
 2746264 305812
create array      VSZ    RSS
 2793496 351916
free array      VSZ    RSS
 2793496 352044
create array      VSZ    RSS
 2839704 398124
free array      VSZ    RSS
 2839704 398252
create array      VSZ    RSS
 2885912 444348
free array      VSZ    RSS
 2885912 444476
create array      VSZ    RSS
 2932120 490556
free array      VSZ    RSS
 2932120 490684
create array      VSZ    RSS
 2978328 536764
free array      VSZ    RSS
 2978328 536900
create array      VSZ    RSS
 3024536 582980
free array      VSZ    RSS
 3024536 583108
```

**Comment by sten22** [comment] 2016-07-08 09:54
the leak depends on array size factor($Na) and iterations count, and not depend how array was created:

```
log_mem_usage("start");

for(1..100) {
    eval 'my sub x' . $_ . ' {
        my $arr = [ ];
        push @$arr, $_ foreach 1 .. $Na;
    };
    x' . $_ . '();';

    log_mem_usage($_);
};

log_mem_usage("leave scope");


start      VSZ    RSS
 2464020   2784
1      VSZ    RSS
 2616856 168012
2      VSZ    RSS
 2663064 214412
3      VSZ    RSS
 2709272 260620
4      VSZ    RSS
 2755480 306828
5      VSZ    RSS
 2801688 353044
6      VSZ    RSS
 2847896 399252
7      VSZ    RSS
 2894104 445460
8      VSZ    RSS
 2940312 491668
9      VSZ    RSS
 2986520 537876
10      VSZ    RSS
 3032728 584084
11      VSZ    RSS
 3078936 630292
12      VSZ    RSS
 3125144 676500
13      VSZ    RSS
 3171352 722708
14      VSZ    RSS
 3217560 735404
15      VSZ    RSS
 3263768 736376
16      VSZ    RSS
 3263768 691996
17      VSZ    RSS
 3263768 690120
18      VSZ    RSS
 3263768 689568
19      VSZ    RSS
 3263768 689568
20      VSZ    RSS
 3263768 689076
21      VSZ    RSS
 3263768 689308
22      VSZ    RSS
 3263768 688864
23      VSZ    RSS
 3263768 732892
24      VSZ    RSS
 3263768 778140
25      VSZ    RSS
 3263768 814164
26      VSZ    RSS
 3263768 800380
27      VSZ    RSS
 3263768 814176
28      VSZ    RSS
 3263768 814192
29      VSZ    RSS
 3263768 814192
```

after reaching ~800mb rss it stop increasing
